cmake_minimum_required(VERSION 3.21)

# Standalone dependency diagnostic: cmake -P check_dependencies.cmake
set(_config "${CMAKE_CURRENT_LIST_DIR}/config.env")
if(NOT EXISTS "${_config}")
    set(_config "${CMAKE_CURRENT_LIST_DIR}/src/config.env")
endif()
if(EXISTS "${_config}")
    file(STRINGS "${_config}" _lines)
    foreach(_line IN LISTS _lines)
        if(_line MATCHES "^[^#].*=.*")
            string(REGEX REPLACE "([^=]+)=(.*)" "\\1;\\2" _pair "${_line}")
            list(GET _pair 0 _key)
            list(GET _pair 1 _value)
            string(REGEX REPLACE "^[\"'](.*)[\"']$" "\\1" _value "${_value}")
            set(${_key} "${_value}")
        endif()
    endforeach()
endif()

foreach(_hint IN ITEMS FREEIMAGE_DIR SDL3_DIR SDL3_TTF_DIR)
    if(DEFINED ${_hint})
        list(PREPEND CMAKE_PREFIX_PATH "${${_hint}}")
        message(STATUS "${_hint} = ${${_hint}}")
    endif()
endforeach()

find_path(FREEIMAGE_HEADER FreeImage.h HINTS "${FREEIMAGE_DIR}" "${FREEIMAGE_DIR}/include" PATHS /usr/include /usr/local/include /opt/homebrew/include)
find_path(SDL3_HEADER SDL3/SDL.h HINTS "${SDL3_DIR}" "${SDL3_DIR}/include" PATHS /usr/include /usr/local/include /opt/homebrew/include)
find_path(SDL3_TTF_HEADER SDL3_ttf/SDL_ttf.h HINTS "${SDL3_TTF_DIR}" "${SDL3_TTF_DIR}/include" PATHS /usr/include /usr/local/include /opt/homebrew/include)

foreach(_dependency IN ITEMS FREEIMAGE SDL3 SDL3_TTF)
    if(${_dependency}_HEADER)
        message(STATUS "✓ ${_dependency} headers: ${${_dependency}_HEADER}")
    else()
        message(WARNING "✗ ${_dependency} headers not found")
    endif()
endforeach()

message(STATUS "Provide FREEIMAGE_DIR, SDL3_DIR, and SDL3_TTF_DIR in config.env, or add their prefixes to CMAKE_PREFIX_PATH.")
